repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        args: [--fix]
        verbose: true
        stages: [pre-commit]
      - id: ruff-format
        verbose: true
        stages: [pre-commit]

  - repo: https://github.com/AndreiCostinescu/DevTools
    rev: b0b747598e766e885d51c4f48ee19a27bae9bfe4
    hooks:
      - id: license-header-check-python
        stages: [pre-commit]
      - id: dco-check
