repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        args: [--fix]
        verbose: true
        stages: [pre-commit]
      - id: ruff-format
        verbose: true
        stages: [pre-commit]

  - repo: https://github.com/AndreiCostinescu/DevTools
    rev: 77dbbfa9a9d7693e5fe796b2b84478557c8f78aa
    hooks:
      - id: license-header-check-python
        stages: [pre-commit]
      - id: dco-check
