[tox]
envlist = py310, py311, py312, py313
isolated_build = true

[testenv]
deps =
    pytest>=7
    pytest-cov
    frozendict>=2.4.7
commands =
    pytest tests/ --cov=concept_hierarchy --cov-report=term-missing {posargs}
