[tox]
envlist = py37, py38, py39, py310, py311, py312
isolated_build = true

[testenv]
deps =
    pytest>=7
    pytest-cov
    frozendict>=2.3
commands =
    pytest tests/ --cov=concept_hierarchy --cov-report=term-missing {posargs}
