# Copyright 2026 ConceptHierarchy Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
cpp.py — C++ code-generation backend.

Generates a C++ header file with a class hierarchy that mirrors the
ConceptHierarchy definition.  Each concept becomes a struct/class;
inheritance follows the parent → child relationships; attributes become
public data members.
"""

from typing import Dict, List, Optional

from concept_hierarchy.backends.base import BaseBackend
from concept_hierarchy.models import Concept, ConceptHierarchyModel

# ---------------------------------------------------------------------------
# Simple type mapping: ConceptHierarchy type strings → C++ type strings.
# Extend this dict as the type system grows.
# ---------------------------------------------------------------------------
_TYPE_MAP: Dict[str, str] = {
    "int": "int",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "string": "std::string",
    "str": "std::string",
}

_HEADER = """\
// Auto-generated by ConceptHierarchy compiler — do not edit by hand.
#pragma once

#include <string>

"""


class CppBackend(BaseBackend):
    """Generate a C++ header from a :class:`ConceptHierarchyModel`."""

    def generate(self, model: ConceptHierarchyModel) -> str:
        lines: List[str] = [_HEADER]

        # Topologically sorted so base classes always appear before derived ones.
        ordered = _topological_sort(model)

        for concept in ordered:
            lines.append(self._render_concept(concept))

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _render_concept(self, concept: Concept) -> str:
        parts: List[str] = []

        if concept.description:
            parts.append(f"// {concept.description}")

        if concept.parent:
            parts.append(f"struct {concept.name} : public {concept.parent} {{")
        else:
            parts.append(f"struct {concept.name} {{")

        for attr_name, attr_type in concept.attributes.items():
            cpp_type = _TYPE_MAP.get(attr_type, attr_type)
            parts.append(f"    {cpp_type} {attr_name};")

        parts.append("};\n")
        return "\n".join(parts)


# ---------------------------------------------------------------------------
# Topological sort (Kahn's algorithm)
# ---------------------------------------------------------------------------

def _topological_sort(model: ConceptHierarchyModel) -> List[Concept]:
    from collections import deque

    concepts: Dict[str, Concept] = {c.name: c for c in model.concepts}
    # children[parent] = list of child names
    children: Dict[str, List[str]] = {name: [] for name in concepts}
    in_degree: Dict[str, int] = {name: 0 for name in concepts}

    for concept in model.concepts:
        if concept.parent is not None:
            children[concept.parent].append(concept.name)
            in_degree[concept.name] += 1

    queue: deque[str] = deque(
        name for name, degree in in_degree.items() if degree == 0
    )
    result: List[Concept] = []

    while queue:
        name = queue.popleft()
        result.append(concepts[name])
        for child in children[name]:
            in_degree[child] -= 1
            if in_degree[child] == 0:
                queue.append(child)

    return result
