# Copyright 2026 ConceptHierarchy Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
cpp.py — C++ code-generation backend.

Generates a C++ header file with a class hierarchy that mirrors the
ConceptHierarchy definition.  Each concept becomes a struct/class;
inheritance follows the parent → child relationships; attributes become
public data members.
"""

from concept_hierarchy.backends.base import BaseBackend
from concept_hierarchy.definitions.concept_definition import ConceptDefinition
from concept_hierarchy.definitions.concept_definition_domain_concept import (
    DomainConceptDefinition,
    PropertyDefinitionKeywords,
)
from concept_hierarchy.models import ConceptHierarchyModel
from concept_hierarchy.utils import topological_sort

# ---------------------------------------------------------------------------
# Simple type mapping: ConceptHierarchy type strings → C++ type strings.
# Extend this dict as the type system grows.
# ---------------------------------------------------------------------------
_TYPE_MAP: dict[str, str] = {
    "int": "int",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "string": "std::string",
    "str": "std::string",
}

_HEADER = """\
// Auto-generated by ConceptHierarchy compiler — do not edit by hand.
#pragma once

#include <string>

"""


class CppBackend(BaseBackend):
    """Generate a C++ header from a :class:`ConceptHierarchyModel`."""

    def generate(self, model: ConceptHierarchyModel) -> str:
        lines: list[str] = [_HEADER]

        # Topologically sorted so base classes always appear before derived ones.
        ordered, _roots = topological_sort({c: c_data.parents for c, c_data in model.concepts.items()})

        for concept_name in ordered:
            lines.append(CppBackend.render_concept(model.concepts[concept_name]))

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def render_concept(concept: ConceptDefinition) -> str:
        parts: list[str] = []

        if concept.description:
            parts.append(f"// {concept.description}")

        if concept.parents:
            bases = ", ".join(f"public {p}" for p in concept.parents)
            parts.append(f"struct {concept.name} : {bases} {{")
        else:
            parts.append(f"struct {concept.name} {{")

        if isinstance(concept, DomainConceptDefinition):
            for prop_name, prop_type in concept.properties.items():
                assert isinstance(prop_type, dict)
                prop_value_domain = prop_type[PropertyDefinitionKeywords.VALUE_DOMAIN]
                cpp_type = _TYPE_MAP.get(prop_value_domain, prop_value_domain)
                parts.append(f"    {cpp_type} {prop_name};")

        parts.append("};\n")
        return "\n".join(parts)
