# Copyright 2026 ConceptHierarchy Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
cpp.py — C++ code-generation backend.

Generates a C++ header file with a class hierarchy that mirrors the
ConceptHierarchy definition.  Each concept becomes a struct/class;
inheritance follows the parent → child relationships; attributes become
public data members.
"""

from concept_hierarchy.backends.base import BaseBackend
from concept_hierarchy.data.concept_hierarchy import ConceptHierarchy
from concept_hierarchy.definitions.concept_definition import ConceptDefinition
from concept_hierarchy.definitions.concept_definition_domain_concept import (
    DomainConceptDefinition,
    PropertyDefinitionKeywords,
)
from concept_hierarchy.definitions.concept_hierarchy import ConceptHierarchyDefinition
from concept_hierarchy.utils import topological_sort

# ---------------------------------------------------------------------------
# Simple type mapping: ConceptHierarchy type strings → C++ type strings.
# Extend this dict as the type system grows.
# ---------------------------------------------------------------------------
_TYPE_MAP: dict[str, str] = {
    "int": "int",
    "float": "float",
    "double": "double",
    "bool": "bool",
    "string": "std::string",
    "str": "std::string",
}

_HEADER = """\
// Auto-generated by ConceptHierarchy compiler — do not edit by hand.
#pragma once

#include <string>

"""


class CppBackend(BaseBackend):
    """Generate a C++ header from a :class:`ConceptHierarchy`."""

    def generate(self, model: ConceptHierarchy) -> str:
        lines: list[str] = [_HEADER]

        # Topologically sorted so base classes always appear before derived ones.
        ordered, _roots = topological_sort({c: c_data.parents for c, c_data in model.ch.concepts.items()})

        for concept_name in ordered:
            lines.append(CppBackend.render_concept(model.ch.concepts[concept_name]))

        aliases = CppBackend.render_aliases(model.ch)
        if aliases:
            lines.append(aliases)

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def render_aliases(ch: ConceptHierarchyDefinition) -> str:
        """
        The ``using`` declarations, one per alias.

        An alias is a name, not an entity, so it emits a declaration and never a second struct -- which is
        what keeps the generated header free of the duplicated definitions the old cloning produced. The
        alias containers are the whole of the metadata this needs, which is why they live on the definition
        the backend is handed.

        Emitted after every struct, so each names something already declared. The target names are written
        unmapped, exactly as ``render_concept`` names the structs, so that a declaration refers to the
        struct that is actually there.

        Global-variable aliases are deliberately absent: ``using`` introduces a *type* name in C++, and this
        backend does not emit global variables at all. How a variable's second name should be spelled is for
        whoever emits the variables.
        """
        declarations = [f"using {alias} = {concept};" for alias, concept in ch.concept_aliases.items()]
        declarations += [f"using {alias} = {alias_type};" for alias, alias_type in ch.type_aliases.items()]
        if not declarations:
            return ""
        return "// Aliases: further names for the concepts and types declared above.\n" + "\n".join(declarations) + "\n"

    @staticmethod
    def render_concept(concept: ConceptDefinition) -> str:
        parts: list[str] = []

        if concept.description:
            parts.append(f"// {concept.description}")

        if concept.parents:
            bases = ", ".join(f"public {p}" for p in concept.parents)
            parts.append(f"struct {concept.name} : {bases} {{")
        else:
            parts.append(f"struct {concept.name} {{")

        if isinstance(concept, DomainConceptDefinition):
            for prop_name, prop_type in concept.properties.items():
                assert isinstance(prop_type, dict)
                prop_value_domain = prop_type[PropertyDefinitionKeywords.VALUE_DOMAIN]
                cpp_type = _TYPE_MAP.get(prop_value_domain, prop_value_domain)
                parts.append(f"    {cpp_type} {prop_name};")

        parts.append("};\n")
        return "\n".join(parts)
